I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script call
    call expression semana from _call_expression
  File "game/weeks/week_3/week_three.rpy", line 11, in script call
    call semana3_dia20
  File "game/weeks/week_3/day_20.rpy", line 6, in script call
    call prepare_battle_2
  File "game/battlesys/labels/prepare_battle.rpy", line 66, in script call
    call turn_start
  File "game/battlesys/labels/turn_start.rpy", line 11, in script call
    call battle_menu
  File "game/battlesys/labels/menu_battle.rpy", line 11, in script call
    call start_battle_phase
  File "game/battlesys/labels/menu_battle.rpy", line 47, in script call
    call bp_player_turn
  File "game/battlesys/labels/player_turn.rpy", line 79, in script call
    call bp_enemy_turn
  File "game/battlesys/labels/enemy_turn.rpy", line 77, in script call
    call check_status_condition
  File "game/battlesys/labels/player_turn.rpy", line 145, in script
    python:
  File "game/battlesys/labels/player_turn.rpy", line 152, in <module>
    se.effect('enemy', battleState, battlePhase)
  File "game/weeks/week_0/week_zero.rpy", line 53, in poison_effect
    renpy.say('', '[((battleState.enemy_team_current_stats)[0]).enemy_name] is hurt by being calculated!')
KeyError: '((battleState'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script call
    call expression semana from _call_expression
  File "game/weeks/week_3/week_three.rpy", line 11, in script call
    call semana3_dia20
  File "game/weeks/week_3/day_20.rpy", line 6, in script call
    call prepare_battle_2
  File "game/battlesys/labels/prepare_battle.rpy", line 66, in script call
    call turn_start
  File "game/battlesys/labels/turn_start.rpy", line 11, in script call
    call battle_menu
  File "game/battlesys/labels/menu_battle.rpy", line 11, in script call
    call start_battle_phase
  File "game/battlesys/labels/menu_battle.rpy", line 47, in script call
    call bp_player_turn
  File "game/battlesys/labels/player_turn.rpy", line 79, in script call
    call bp_enemy_turn
  File "game/battlesys/labels/enemy_turn.rpy", line 77, in script call
    call check_status_condition
  File "game/battlesys/labels/player_turn.rpy", line 145, in script
    python:
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/battlesys/labels/player_turn.rpy", line 152, in <module>
    se.effect('enemy', battleState, battlePhase)
  File "game/weeks/week_0/week_zero.rpy", line 53, in poison_effect
    renpy.say('', '[((battleState.enemy_team_current_stats)[0]).enemy_name] is hurt by being calculated!')
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\exports.py", line 1472, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\defaultstore.py", line 418, in say
    who(what, interact=interact, *args, **kwargs)
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "D:\Users\Luiz Sergio\Documents\GitHub\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: '((battleState'

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
ES_Weeks_Impl 1.0
Sun Oct 29 21:55:17 2023
