I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 47, in script
    pyt "Ei, [P-name], você tem algo que goste de fazer no seu tempo livre?"
KeyError: 'P-name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 47, in script
    pyt "Ei, [P-name], você tem algo que goste de fazer no seu tempo livre?"
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "C:\Users\User\Desktop\renpy-8.1.2-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'P-name'

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.2.23090503
ES_Weeks_Impl 1.0
Mon Oct 23 19:35:23 2023
